# Generated by Django 5.2.6 on 2025-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_description",
                    models.TextField(blank=True, verbose_name="시놉시스"),
                ),
                ("content_act", models.CharField(verbose_name="출연진")),
                ("content_dir", models.CharField(verbose_name="감독")),
                ("content_ott", models.CharField(verbose_name="OTT")),
                ("content_genre", models.CharField(verbose_name="장르")),
                ("post_image", models.ImageField(upload_to="", verbose_name="포스터")),
            ],
        ),
    ]
