# Generated by Django 5.2.6 on 2025-09-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="작품제목"
                    ),
                ),
                (
                    "content_description",
                    models.TextField(blank=True, null=True, verbose_name="시놉시스"),
                ),
                (
                    "content_act",
                    models.CharField(blank=True, null=True, verbose_name="출연진"),
                ),
                (
                    "content_dir",
                    models.CharField(blank=True, null=True, verbose_name="감독"),
                ),
                (
                    "content_ott",
                    models.CharField(blank=True, null=True, verbose_name="OTT"),
                ),
                (
                    "content_genre",
                    models.CharField(blank=True, null=True, verbose_name="장르"),
                ),
                (
                    "post_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="포스터"
                    ),
                ),
                (
                    "content_year",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="개봉년도"
                    ),
                ),
            ],
        ),
    ]
