# Generated by Django 5.2.6 on 2025-09-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_content_act_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_genre",
            field=models.CharField(blank=True, null=True, verbose_name="장르"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="개봉년도"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="포스터"
            ),
        ),
    ]
