# Generated by Django 5.2.6 on 2025-09-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="review.review",
                verbose_name="게시글",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
    ]
