# Generated by Django 5.2.6 on 2025-09-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        ("review", "0004_alter_review_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="post.post",
                verbose_name="작품명",
            ),
        ),
    ]
