# Generated by Django 5.2.5 on 2025-09-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="like_posts",
            field=models.ManyToManyField(
                blank=True,
                related_name="like_user",
                to="post.post",
                verbose_name="좋아요 누른 Post 목록",
            ),
        ),
    ]
