# Generated by Django 5.2.6 on 2025-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amazon_movieRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(blank=True, max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amazon_tvRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(blank=True, max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disney_Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Netflix_movieRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Netflix_tvRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wavve_movieRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(max_length=10, verbose_name="기간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wavve_tvRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_rank", models.CharField(max_length=5, verbose_name="순위")),
                (
                    "content_name",
                    models.CharField(max_length=50, verbose_name="작품제목"),
                ),
                (
                    "content_period",
                    models.CharField(max_length=10, verbose_name="기간"),
                ),
            ],
        ),
    ]
