# Generated by Django 5.2.6 on 2025-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Last_update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_date", models.DateField(auto_now_add=True, verbose_name="날짜")),
            ],
        ),
    ]
