# Generated by Django 5.2.6 on 2025-09-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0002_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="netflix_movierank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
        migrations.AddField(
            model_name="netflix_tvrank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
    ]
