# Generated by Django 5.2.6 on 2025-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0003_netflix_movierank_content_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazon_movierank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
        migrations.AddField(
            model_name="amazon_tvrank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
    ]
