# Generated by Django 5.2.6 on 2025-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0004_amazon_movierank_content_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disney_rank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
    ]
