# Generated by Django 5.2.6 on 2025-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0005_disney_rank_content_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="wavve_movierank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
        migrations.AddField(
            model_name="wavve_tvrank",
            name="content_img",
            field=models.CharField(blank=True, verbose_name="이미지"),
        ),
    ]
