# Generated by Django 5.2.6 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0006_wavve_movierank_content_img_wavve_tvrank_content_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="last_update",
            name="last_dummy",
            field=models.CharField(blank=True, verbose_name="create용 컬럼"),
        ),
    ]
