# Generated by Django 5.2.6 on 2025-09-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0007_last_update_last_dummy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="last_update",
            name="last_dummy",
        ),
    ]
